services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    mem_limit: 512m
    networks:
      - net

  backend:
    build:
      context: ../BlinkXES-backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      ../BlinkXES-backend/.env
    ports:
      - "7788:7788"
    networks:
      - net

  frontend:
    build:
      context: ../BlinkEXS
      dockerfile: .dockerfile
    container_name: frontend
    environment:
      VITE_BACKEND_URL: api
      VITE_ALLOW_URL: drtyui.ru

    ports:
      - "5173:5173"
    networks:
      - net


volumes:
  postgres-data:

networks:
  net:
    driver: bridge
